(add-to-list 'load-path "/usr/local/go/misc/emacs" t)
(add-to-list 'load-path "~/Code/go/src/github.com/nsf/gocode/emacs" t)

(add-hook 'go-mode-hook (lambda ()
                          (local-set-key (kbd "\C-c\C-r") 'go-remove-unused-imports)))
(add-hook 'go-mode-hook (lambda ()
                          (local-set-key (kbd "\C-ci") 'go-goto-imports)))
(add-hook 'go-mode-hook (lambda ()
                          (setq tab-width 4)))
(add-hook 'before-save-hook 'gofmt-before-save)
